
package com.elusivehawk.caelum.render.gl;

/**
 * 
 * 
 * 
 * @author Elusivehawk
 */
public enum GLEnumTexBind
{
	GL_TEXTURE_BINDING_1D(GLConst.GL_TEXTURE_BINDING_1D),
	GL_TEXTURE_BINDING_2D(GLConst.GL_TEXTURE_BINDING_2D),
	GL_TEXTURE_BINDING_3D(GLConst.GL_TEXTURE_BINDING_3D),
	GL_TEXTURE_BINDING_1D_ARRAY(GLConst.GL_TEXTURE_BINDING_1D_ARRAY),
	GL_TEXTURE_BINDING_2D_ARRAY(GLConst.GL_TEXTURE_BINDING_2D_ARRAY),
	GL_TEXTURE_BINDING_RECTANGLE(GLConst.GL_TEXTURE_BINDING_RECTANGLE),
	GL_TEXTURE_BINDING_BUFFER(GLConst.GL_TEXTURE_BINDING_BUFFER),
	GL_TEXTURE_BINDING_CUBE_MAP(GLConst.GL_TEXTURE_BINDING_CUBE_MAP),
	GL_TEXTURE_BINDING_CUBE_MAP_ARRAY(GLConst.GL_TEXTURE_BINDING_CUBE_MAP_ARRAY),
	GL_TEXTURE_BINDING_2D_MULTISAMPLE(GLConst.GL_TEXTURE_BINDING_2D_MULTISAMPLE),
	GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY(GLConst.GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY);
	
	public final int glCode;
	
	@SuppressWarnings("unqualified-field-access")
	GLEnumTexBind(int gl)
	{
		glCode = gl;
		
	}
	
}
